repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: local
    hooks:
    -   id: gdsctipt-formatter
        name: Gdstript formatter
        entry: gdformat
        pass_filenames: true
        language: system
        files: \.gd$
    -   id: gdsctipt-linter
        name: Gdstript linter
        entry: rm lint.log; gdlint
        pass_filenames: true
        language: system
        files: \.gd$
        log_file: lint.log
